### ISSUE TITLE
Admin panel broken?

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [cookiecutter/cookiecutter-django#3497]
## What happened?

I think the admin panel, upon login, is broken as apps aren't being properly registered.

To reproduce, use docker and try to access the login panel. Logs given below.

## What should've happened instead?

Admin should load

## Additional details

* Host system configuration:
    * Version of cookiecutter CLI (get it with `cookiecutter --version`):
    * OS name and version:

      On Linux, run
      ```bash
      lsb_release -a 2> /dev/null || cat /etc/redhat-release 2> /dev/null || cat /etc/*-release 2> /dev/null || cat /etc/issue 2> /dev/null
      ```

      On MacOs, run
      ```bash
      sw_vers
      ```

      On Windows, via CMD, run
      ```
      systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
      ```

      ```bash
      # Insert here the OS name and version

      ```

    * Python version, run `python3 -V`:
    * Docker version (if using Docker), run `docker --version`:
    * docker-compose version (if using Docker), run `docker-compose --version`:
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and MacOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)
    ```json
    "timezone": "UTC",
    "windows": "n",
    "use_pycharm": "y",
    "use_docker": "y",
    "postgresql_version": "14.1",
    "js_task_runner": "None",
    "cloud_provider": "AWS",
    "mail_service": "Amazon SES",
    "use_async": "n",
    "use_drf": "y",
    "custom_bootstrap_compilation": "n",
    "use_compressor": "y",
    "use_celery": "y",
    "use_mailhog": "y",
    "use_sentry": "y",
    "use_whitenoise": "n",
    "use_heroku": "n",
    "ci_tool": "Github",
    "keep_local_envs_in_vcs": "y",
    "debug": "n",
    "_template": "gh:pydanny/cookiecutter-django"
    ```
<summary>
Logs:

```
django_1        | 172.22.0.1 - - [26/Dec/2021 16:47:23] "GET /admin/ HTTP/1.1" 500 -
django_1        | Traceback (most recent call last):
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
django_1        |     return self.application(environ, start_response)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
django_1        |     response = self.get_response(request)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 130, in get_response
django_1        |     response = self._middleware_chain(request)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
django_1        |     response = response_for_exception(request, exc)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
django_1        |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
django_1        |     return debug.technical_500_response(request, *exc_info)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
django_1        |     raise exc_value.with_traceback(tb)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
django_1        |     response = get_response(request)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
django_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1        |   File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
django_1        |     return func(*args, **kwds)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 250, in wrapper
django_1        |     return self.admin_view(view, cacheable)(*args, **kwargs)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
django_1        |     response = view_func(request, *args, **kwargs)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
django_1        |     response = view_func(request, *args, **kwargs)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 232, in inner
django_1        |     return view(request, *args, **kwargs)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
django_1        |     response = view_func(request, *args, **kwargs)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 522, in index
django_1        |     app_list = self.get_app_list(request)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 505, in get_app_list
django_1        |     app_dict = self._build_app_dict(request)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 487, in _build_app_dict
django_1        |     'app_url': reverse(
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/urls/base.py", line 86, in reverse
django_1        |     return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
django_1        |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
django_1        |     raise NoReverseMatch(msg)
django_1        | django.urls.exceptions.NoReverseMatch: Reverse for 'app_list' with keyword arguments '{'app_label': 'trending'}' not found. 1 pattern(s) tried: ['admin/(?P<app_label>auth|sites|account|socialaccount|django_celery_beat)/$']
django_1        | 172.22.0.1 - - [26/Dec/2021 16:47:23] "GET /admin/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
django_1        | 172.22.0.1 - - [26/Dec/2021 16:47:23] "GET /admin/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
django_1        | 172.22.0.1 - - [26/Dec/2021 16:47:23] "GET /admin/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
django_1        | 172.22.0.1 - - [26/Dec/2021 16:47:24] "GET /admin/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
```

<details>
<pre>
$ cookiecutter https://github.com/cookiecutter/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by browniebroke** [comment]
I just tried to reproduce, but I cannot. It works fine on my end with a vanilla project with similar options:

```
{
  "cookiecutter": {
    "timezone": "UTC",
    "windows": "n",
    "use_pycharm": "y",
    "use_docker": "y",
    "postgresql_version": "14.1",
    "js_task_runner": "None",
    "cloud_provider": "AWS",
    "mail_service": "Mailgun",
    "use_async": "n",
    "use_drf": "y",
    "custom_bootstrap_compilation": "n",
    "use_compressor": "y",
    "use_celery": "y",
    "use_mailhog": "n",
    "use_sentry": "y",
    "use_whitenoise": "n",
    "use_heroku": "n",
    "ci_tool": "Github",
    "keep_local_envs_in_vcs": "y",
    "debug": "n"
  }
}
```

I see your error is mentioning an `app_label` called "trending", is it something you've added?

```
django.urls.exceptions.NoReverseMatch: Reverse for 'app_list' with keyword arguments '{'app_label': 'trending'}' not found. 1 pattern(s) tried: ['admin/(?P<app_label>auth|sites|account|socialaccount|django_celery_beat)/$']
```

**Comment by Andrew-Chen-Wang** [comment]
Thanks for the quick response. Yes it is an app. It mentions trending since I enabled a single model to be registered from that app. All app_name in urls.py are fine. apps.py LGTM. Migrations are created properly. In setttings base.py. APP_DIR=True. Options only includes context_processors. DIRS is still a list with APPS_DIR/templates. I have not added an admin directory under the templates directory. Perhaps there is something wrong with my TEMPLATES settings...? It looks the same to me besides the allauth_contextprocessor

**Comment by browniebroke** [comment]
Could you reproduce the problem in a public repo? A bit hard to tell otherwise...

**Comment by Andrew-Chen-Wang** [comment]
@browniebroke I can't seem to reproduce either, so I just invited you to the repo.

**Comment by Andrew-Chen-Wang** [comment]
Potentially a docker cache/image problem. Closing since it can't exactly are reproduced.
