### ISSUE TITLE
Docs container cannot recognize new app

### ISSUE THREAD

**Issue by pfk-beta** [cookiecutter/cookiecutter-django#3720]
## What happened?
I have added new app, with startapp command. It has create directory inside root folder of project. I'm getting stacktrace from docs container, that it canot find created module:
```
| Running Sphinx v4.5.0
| 
| Configuration error:
| There is a programmable error in your configuration file:
| 
| Traceback (most recent call last):
|   File "/usr/local/lib/python3.9/site-packages/sphinx/config.py", line 332, in eval_config_file
|     exec(code, namespace)
|   File "/docs/conf.py", line 26, in <module>
|     django.setup()
|   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
|     apps.populate(settings.INSTALLED_APPS)
|   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
|     app_config = AppConfig.create(entry)
|   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 224, in create
|     import_module(entry)
|   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
|     return _bootstrap._gcd_import(name[level:], package, level)
|   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
|   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
|   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
| ModuleNotFoundError: No module named 'core'
| 
| Command exited with exit code: 2
```
Other things are working correctly, I have created models, views, forms, migrations, admin, etc. - it works.

My main docker images are using ubuntu, instead of python-slim.

**Comment by pfk-beta** [comment]
Can be solved by removing docs service - solved.
