### ISSUE TITLE
environ was not find by heroku

### ISSUE THREAD

**Issue by TrevyRugema** [cookiecutter/cookiecutter-django#3793]
tried to deploy my app but i encounter this issue ,think i did correctly!
```
remote: -----> $ python manage.py collectstatic --noinput
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python3.10/site-packages/environ/environ.py", line 403, in get_value
remote:            value = self.ENVIRON[var_name]
remote:          File "/app/.heroku/python/lib/python3.10/os.py", line 679, in __getitem__
remote:            raise KeyError(key) from None
remote:        KeyError: 'SECRET_KEY'
remote:        The above exception was the direct cause of the following exception:
remote:        Traceback (most recent call last):
remote:          File "/tmp/build_d1c609fa/manage.py", line 16, in <module>
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
remote:            self.fetch_command(subcommand).run_from_argv(self.argv)
remote:          File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 266, in fetch_command
remote:            settings.INSTALLED_APPS
remote:          File "/app/.heroku/python/lib/python3.10/site-packages/django/conf/__init__.py", line 87, in __getattr__
remote:            self._setup(name)
remote:          File "/app/.heroku/python/lib/python3.10/site-packages/django/conf/__init__.py", line 74, in _setup
remote:            self._wrapped = Settings(settings_module)
remote:          File "/app/.heroku/python/lib/python3.10/site-packages/django/conf/__init__.py", line 183, in __init__
remote:            mod = importlib.import_module(self.SETTINGS_MODULE)
remote:          File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
remote:            return _bootstrap._gcd_import(name[level:], package, level)
remote:          File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
remote:          File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
remote:          File "<frozen importlib._bootstrap_external>", line 883, in exec_module
remote:          File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
remote:          File "/tmp/build_d1c609fa/btre/settings.py", line 21, in <module>
remote:            SECRET_KEY =env('SECRET_KEY')
remote:          File "/app/.heroku/python/lib/python3.10/site-packages/environ/environ.py", line 197, in __call__
remote:            return self.get_value(
remote:          File "/app/.heroku/python/lib/python3.10/site-packages/environ/environ.py", line 407, in get_value
remote:            raise ImproperlyConfigured(error_msg) from exc
remote:        django.core.exceptions.ImproperlyConfigured: Set the SECRET_KEY environment variable
```

**Comment by browniebroke** [comment]
Looks like you did not set the environment variables before deploying. Did you follow [our page](https://cookiecutter-django.readthedocs.io/en/latest/deployment-on-heroku.html)?

You might have, but the line with the problem doesn't look like it was generated by cookiecutter-django:

```
# btre/settings.py
SECRET_KEY =env('SECRET_KEY')
```

Which is quite different from how the secret key is set on prod:

https://github.com/cookiecutter/cookiecutter-django/blob/ee20b4d156d2e4165d6f69331da4dcbc8c526337/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/production.py#L19

Did you change it? If so, you need to set the environment variables accordingly.

Hope that helps 😄
