### ISSUE TITLE
python manage.py compilemessages did not complete successfully

### ISSUE THREAD

**Issue by RasmusSecher** [cookiecutter/cookiecutter-django#4386]
## What happened?
`docker compose -f production.yml build` throws error: python manage.py compilemessages did not complete successfully, on a fresh install. 

## What should've happened instead?
Should have completed the build the command with no errors

## Additional details

- Host system configuration:

  - Version of cookiecutter CLI (get it with `cookiecutter --version`): 2.1.1
  - OS name and version:
    ProductName:		macOS
    ProductVersion:		13.2
    BuildVersion:		22D49

  - Python version, run `python3 -V`: 3.9.13
  - Docker version (if using Docker), run `docker --version`: 20.10.17
  - docker-compose version (if using Docker), run `docker-compose --version`: 2.17.3

- Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and macOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)

```json
{
  "cookiecutter": {
    "project_name": "x",
    "project_slug": "x",
    "description": "x",
    "author_name": "x x",
    "domain_name": "x",
    "email": "x@x.x",
    "version": "0.1.0",
    "open_source_license": "Not open source",
    "username_type": "email",
    "timezone": "UTC",
    "windows": "n",
    "use_pycharm": "n",
    "use_docker": "y",
    "postgresql_version": "14",
    "cloud_provider": "None",
    "mail_service": "Mailgun",
    "use_async": "n",
    "use_drf": "n",
    "frontend_pipeline": "None",
    "use_celery": "y",
    "use_mailhog": "y",
    "use_sentry": "y",
    "use_whitenoise": "y",
    "use_heroku": "n",
    "ci_tool": "Github",
    "keep_local_envs_in_vcs": "y",
    "debug": "n",
  }
}
```

<details>
<summary>
Terminal
</summary>

```
docker-compose -f production.yml build

[+] Building 2.0s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 303B                                                              0.0s
 => [internal] load .dockerignore                                                                 0.0s
 => => transferring context: 211B                                                                 0.0s
 => [internal] load metadata for docker.io/library/postgres:14                                    1.9s
 => [internal] load build context                                                                 0.0s
 => => transferring context: 1.20kB                                                               0.0s
 => [1/4] FROM docker.io/library/postgres:14@sha256:af8b776d4b97636bc4844075d4d6e93df1eed120d481  0.0s
 => CACHED [2/4] COPY ./compose/production/postgres/maintenance /usr/local/bin/maintenance        0.0s
 => CACHED [3/4] RUN chmod +x /usr/local/bin/maintenance/*                                        0.0s
 => CACHED [4/4] RUN mv /usr/local/bin/maintenance/* /usr/local/bin     && rmdir /usr/local/bin/  0.0s
 => exporting to image                                                                            0.0s
 => => exporting layers                                                                           0.0s
 => => writing image sha256:7409a67665eb045d08cf7fba4360308adcab8e630cd7d8df164ba2424ce43efe      0.0s
 => => naming to docker.io/library/[redacted]                            0.0s
[+] Building 0.0s (0/0)
[+] Building 0.0s (0/0)
[+] Building 0.0s (0/0)
[+] Building 0.2s (2/3)
 => [internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 2.74kB                                                            0.0s
 => [internal] load .dockerignore                                                                 0.0s
 => => transferring context: 211B                                                                 0.0s
[+] Building 0.1s (2/3)
 => [internal] load build definition from Dockerfile                                              0.0s
[+] Building 2.4s (31/31) FINISHED
 => [internal] load .dockerignore                                                                 0.0s
 => => transferring context: 211B                                                                 0.0s
 => [internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 2.74kB                                                            0.0s
 => [internal] load metadata for docker.io/library/python:3.11.4-slim-bullseye                    1.6s
 => [python 1/1] FROM docker.io/library/python:3.11.4-slim-bullseye@sha256:1966141ab594e175852a0  0.0s
 => [internal] load build context                                                                 0.0s
 => => transferring context: 15.13kB                                                              0.0s
 => CACHED [python-run-stage  1/23] WORKDIR /app                                                  0.0s
 => CACHED [python-run-stage  2/23] RUN addgroup --system django     && adduser --system --ingro  0.0s
 => CACHED [python-run-stage  3/23] RUN apt-get update && apt-get install --no-install-recommend  0.0s
 => CACHED [python-build-stage 1/3] RUN apt-get update && apt-get install --no-install-recommend  0.0s
 => CACHED [python-build-stage 2/3] COPY ./requirements .                                         0.0s
 => CACHED [python-build-stage 3/3] RUN pip wheel --wheel-dir /usr/src/app/wheels    -r producti  0.0s
 => CACHED [python-run-stage  4/23] COPY --from=python-build-stage /usr/src/app/wheels  /wheels/  0.0s
 => CACHED [python-run-stage  5/23] RUN pip install --no-cache-dir --no-index --find-links=/whee  0.0s
 => CACHED [python-run-stage  6/23] COPY --chown=django:django ./compose/production/django/entry  0.0s
 => CACHED [python-run-stage  7/23] RUN sed -i 's/\r$//g' /entrypoint                             0.0s
 => CACHED [python-run-stage  8/23] RUN chmod +x /entrypoint                                      0.0s
 => CACHED [python-run-stage  9/23] COPY --chown=django:django ./compose/production/django/start  0.0s
 => CACHED [python-run-stage 10/23] RUN sed -i 's/\r$//g' /start                                  0.0s
 => CACHED [python-run-stage 11/23] RUN chmod +x /start                                           0.0s
 => CACHED [python-run-stage 12/23] COPY --chown=django:django ./compose/production/django/celer  0.0s
 => CACHED [python-run-stage 13/23] RUN sed -i 's/\r$//g' /start-celeryworker                     0.0s
 => CACHED [python-run-stage 14/23] RUN chmod +x /start-celeryworker                              0.0s
 => CACHED [python-run-stage 15/23] COPY --chown=django:django ./compose/production/django/celer  0.0s
 => CACHED [python-run-stage 16/23] RUN sed -i 's/\r$//g' /start-celerybeat                       0.0s
 => CACHED [python-run-stage 17/23] RUN chmod +x /start-celerybeat                                0.0s
 => CACHED [python-run-stage 18/23] COPY ./compose/production/django/celery/flower/start /start-  0.0s
 => CACHED [python-run-stage 19/23] RUN sed -i 's/\r$//g' /start-flower                           0.0s
 => CACHED [python-run-stage 20/23] RUN chmod +x /start-flower                                    0.0s
 => CACHED [python-run-stage 21/23] COPY --chown=django:django . /app                             0.0s
 => CACHED [python-run-stage 22/23] RUN chown django:django /app                                  0.0s
 => ERROR [python-run-stage 23/23] RUN DATABASE_URL=""   DJANGO_SETTINGS_MODULE="config.settings  0.7s
------
 > [python-run-stage 23/23] RUN DATABASE_URL=""   DJANGO_SETTINGS_MODULE="config.settings.test"   python manage.py compilemessages:
#0 0.630 /usr/local/lib/python3.11/site-packages/environ/environ.py:598: UserWarning: Engine not recognized from url: {'NAME': '', 'USER': '', 'PASSWORD': '', 'HOST': '', 'PORT': '', 'ENGINE': ''}
#0 0.630   warnings.warn("Engine not recognized from url: {}".format(config))                     0.0s
#0 0.633 Traceback (most recent call last):                                                       0.0s
#0 0.633   File "/usr/local/lib/python3.11/site-packages/environ/environ.py", line 387, in get_value0s
#0 0.633     value = self.ENVIRON[var_name]                                                       0.0s
#0 0.633             ~~~~~~~~~~~~^^^^^^^^^^library/python:3.11.4-slim-bullseye                    1.7s
#0 0.634   File "<frozen os>", line 679, in __getitem__lim-bullseye@sha256:1966141ab594e175852a0  0.0s
#0 0.634 KeyError: 'CELERY_BROKER_URL'                                                            0.0s
#0 0.634 ansferring context: 15.13kB                                                              0.0s
#0 0.634 The above exception was the direct cause of the following exception:
#0 0.634
#0 0.634 Traceback (most recent call last):
#0 0.634   File "/app/manage.py", line 31, in <module>
#0 0.634     execute_from_command_line(sys.argv)
#0 0.634   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
#0 0.634     utility.execute()
#0 0.634   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
#0 0.634     self.fetch_command(subcommand).run_from_argv(self.argv)
#0 0.634   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
#0 0.634     self.execute(*args, **cmd_options)
#0 0.634   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
#0 0.634     output = self.handle(*args, **options)
#0 0.634              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 0.635   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/compilemessages.py", line 90, in handle
#0 0.635     basedirs.extend(settings.LOCALE_PATHS)
#0 0.635                     ^^^^^^^^^^^^^^^^^^^^^
#0 0.635   File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 92, in __getattr__
#0 0.635     self._setup(name)
#0 0.635   File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 79, in _setup
#0 0.635     self._wrapped = Settings(settings_module)
#0 0.635                     ^^^^^^^^^^^^^^^^^^^^^^^^^
#0 0.635   File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__
#0 0.635     mod = importlib.import_module(self.SETTINGS_MODULE)
#0 0.635           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 0.636   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
#0 0.636     return _bootstrap._gcd_import(name[level:], package, level)
#0 0.636            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 0.636   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
#0 0.636   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
#0 0.636   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
#0 0.636   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
#0 0.636   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
#0 0.636   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
#0 0.636   File "/app/config/settings/test.py", line 5, in <module>
#0 0.636     from .base import *  # noqa
#0 0.636     ^^^^^^^^^^^^^^^^^^^
#0 0.636   File "/app/config/settings/base.py", line 258, in <module>
#0 0.637     CELERY_BROKER_URL = env("CELERY_BROKER_URL")
#0 0.637                         ^^^^^^^^^^^^^^^^^^^^^^^^
#0 0.637   File "/usr/local/lib/python3.11/site-packages/environ/environ.py", line 198, in __call__
#0 0.637     return self.get_value(
#0 0.637            ^^^^^^^^^^^^^^^
#0 0.637   File "/usr/local/lib/python3.11/site-packages/environ/environ.py", line 391, in get_value
#0 0.637     raise ImproperlyConfigured(error_msg) from exc
#0 0.637 django.core.exceptions.ImproperlyConfigured: Set the CELERY_BROKER_URL environment variable
------
[+] Building 2.4s (5/31)
 => [internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 2.74kB                                                            0.0s
 => [internal] load .dockerignore                                                                 0.0s
 => => transferring context: 211B                                                                 0.0s
 => [internal] load metadata for docker.io/library/python:3.11.4-slim-bullseye                    1.7s
 => [python 1/1] FROM docker.io/library/python:3.11.4-slim-bullseye@sha256:1966141ab594e175852a0  0.0s
 => [internal] load build context                                                                 0.0s
[+] Building 0.0s (0/0)
failed to solve: process "/bin/sh -c DATABASE_URL=\"\"   DJANGO_SETTINGS_MODULE=\"config.settings.test\"   python manage.py compilemessages" did not complete successfully: exit code: 1
```
</details>

**Comment by browniebroke** [comment]
Can you try to set the CELERY_BROKER_URL to an empty string like the DATABASE_URL in here:

https://github.com/cookiecutter/cookiecutter-django/blob/554edd43b14a45b6b9767ad3b58c5b909807272e/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django/Dockerfile#L124-L126

**Comment by RasmusSecher** [comment]
> Can you try to set the CELERY_BROKER_URL to an empty string like the DATABASE_URL in here:
> 
> https://github.com/cookiecutter/cookiecutter-django/blob/554edd43b14a45b6b9767ad3b58c5b909807272e/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django/Dockerfile#L124-L126

Settings `CELERY_BROKER_URL="" ` fixes the problem - Thank you very much

```
RUN DATABASE_URL="" \
  CELERY_BROKER_URL="" \
  DJANGO_SETTINGS_MODULE="config.settings.test" \
  python manage.py compilemessages
```
