### ISSUE TITLE
2024.9.6 pyproject.toml python pin too restrictive - change ==3.12 to >=3.12

### ISSUE THREAD

**Issue by rxm7706** [cookiecutter/cookiecutter-django#5359]
https://github.com/cookiecutter/cookiecutter-django/blob/ea4cd48e6cfdcc21f33b92092eebb36dbedd1e4b/pyproject.toml#L17

This PR https://github.com/cookiecutter/cookiecutter-django/pull/5351/files#
pinned python to ==3.12
https://github.com/cookiecutter/cookiecutter-django/pull/5351/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

which fails when you have minor version conflict e..g python =3.12.5

2024.9.5 worked without issues, and still work, this was introduced in 2024.9.6

sample error
```
INFO: pip is looking at multiple versions of cookiecutter-django to determine which version is compatible with other requirements. This could take a while.
Will try a different candidate, due to conflict:
    cookiecutter-django 2024.9.6 depends on Python ==3.12
ERROR: Package 'cookiecutter-django' requires a different Python: 3.12.5 not in '==3.12'
Exception information:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "$PREFIX/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$PREFIX/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 439, in resolve
    raise ResolutionImpossible(self.state.backtrack_causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=RequiresPythonRequirement('==3.12'), parent=LinkCandidate('file://$SRC_DIR'))]
```

**Comment by foarsitter** [comment]
Thx @rxm7706, makes sense!
